---
- name: Sysctl config base
  include_tasks: 'sysctl-config-base.yml'

- name: Sysctl check if key already declared elsewhere
  include_tasks: 'sysctl-check-duplicate-key.yml'

- name: Sysctl check if a module need live upgrade
  include_tasks: 'sysctl-check-live-state.yml'

# @TODO: FIX blacklist or change filename for /etc/sysctl.d/00protected-links.conf
- name: Export config files
  template:
    src: etc/sysctl.d/sysctl_conf.j2
    dest: /etc/sysctl.d/{{ item.key }}.conf
    owner: root
    group: root
    mode: '0644'
  loop: "{{ sysctl.dropin | dict2items }}"
  become: true
