---
- name: Search if key is declared elsewhere
  command: grep -RlE '^{{ item.1.key }}(\s|)=.*' --exclude="{{ item.0.key }}.conf" {{ sysctl.config_dir }}
  loop: "{{ sysctl.dropin | dict2items | flatten_item | subelements('value') }}"
  register: sysctl_dropin_source_conflict
  failed_when: false
  changed_when: False
- fail:
    msg:
      - "Sysctl dropin already declared, please migrate"
      - "{{ item }}"
  loop: "{{ sysctl_dropin_source_conflict.results }}"
  when:
    - item.rc is defined and item.rc == 0
    - not ansible_check_mode
